version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
#      - REDIS_PASSWORD=redis123
    command: [ "redis-server", "--appendonly", "yes" ]

  app:
    build:
        context: .
        dockerfile: Dockerfile
        args:
            - DJANGO_SETTINGS_MODULE=config.settings.docker
    command: bash -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  db-data:
  redis_data: