# Generated by Django 5.0.6 on 2024-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='강의실 이름')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='최대 수용 인원')),
                ('remaining_capacity', models.PositiveIntegerField(verbose_name='남은 수용 인원')),
            ],
            options={
                'verbose_name': '강의실',
                'verbose_name_plural': '강의실 목록',
                'db_table': 'classroom',
            },
        ),
    ]
